### ISSUE TITLE
Over extending application level route

### ISSUE THREAD

**Issue by Tajam** [Tajam/mmucraft-website#1]
Instead of adding an extra route for the login page.

https://github.com/Tajam/mmucraft-website/blob/a6f6c8dad88b385546c34d9430bd96720ad75b46/app.js#L39

Use this route instead.

https://github.com/Tajam/mmucraft-website/blob/a6f6c8dad88b385546c34d9430bd96720ad75b46/app.js#L36

Add the route to the login page in here

https://github.com/Tajam/mmucraft-website/blob/a6f6c8dad88b385546c34d9430bd96720ad75b46/routes/index.js

**Comment by ye-yu** [comment]
ok

**Comment by ye-yu** [comment]
Refactored the code in this commit [9d7b370](https://github.com/Tajam/mmucraft-website/commit/9d7b37006c7a2e6f9893488f26b796e22768e3f6)

Login page template can be loaded and so far no error. Closing.
